import Head from 'next/head';

export const Header = () => {
  return (
    <>
      <Head>
        <title>Pedro's Gallery</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='w-full flex items-center gap-2'>
        <h1 className='text-xl font-bold text-center text-white'>Pedro's SD Gallery</h1>
        <div className='ml-auto flex gap-2'>
          <button className='bg-green-400 text-white px-4 py-2 rounded font-bold text-sm hover:bg-green-500 transition-all'>Add Image</button>
          <button className='bg-white text-gray-400 px-4 py-2 rounded font-bold text-sm hover:opacity-[0.8] transition-all'>Gallery link</button>
        </div>
      </div>
    </>
  );
};
